### ISSUE TITLE
Confidentiality of Slack 

### ISSUE THREAD

**Issue by laches1sm** [nitechdesign/code-of-conduct#13]
I do think the term of not being allowed to mention the NI Tech Slack in public is a bit overkill - it could probably be removed, the paragraph below it that states "be careful what you post, as this is a public Slack anyone with a login can see and access" could possibly suffice.

**Comment by u1f35c** [comment]
#general has 1342 members on it. There's no reasonable expectation of privacy. I'd liken it to being in a coffee shop or at the pub. It's bad netiquette to talk about it outside of the channels, but there's no way to police it, there's no way to be sure who's read what you've said and the CoC should be worded more in this fashion I think.

Equally the sign up link has been posted to public mailing lists and on Twitter, so I think the cat is out of the bag on the existence of it. In fact *mo* posted the link on Twitter.

**Comment by mauricerkelly** [comment]
Agreed. The initial Code of Conduct was a boilerplate that I adapted, and either overlooked or didn't fully comprehend the inclusion of that statement.

**Comment by mauricerkelly** [comment]
Thanks for the contribution @becca1993. PR #15 has been merged to address it.

![PARTAY!](https://railsgirlssummerofcode.org/img/blog/2016/l1ghtsab3r-partyparrot.gif)

**Comment by laches1sm** [comment]
No problem! :D and thank you for the parrot :3
