### ISSUE TITLE
CoC needs a SFW section.

### ISSUE THREAD

**Issue by paulgregg** [nitechdesign/code-of-conduct#27]
The current CoC has two main sections:
- Harassment
- Spam.

All appropriate or verboten behaviours are within the context of these two areas.

It is apparent (at least to me) that the community does not explicitly call out what is appropriate behaviour in all channels when that behaviour is neither harassment nor spam.
Specifically, a comment that paraphrased a tweet (from twitter, by an admin no less) was moderated out by that same admin. Yet it did not breach any CoC clause.

I propose that we explicitly add a section on Appropriate behaviour that specifically calls out that all activity should be 'Safe For Work'.  Sexist jokes, sexist comments, sexual or adult images are explicitly forbidden. Any material considered to be NSFW is forbidden.

**Comment by andrewbolster** [comment]
Would you like to raise a PR to suggest what language would suitably encircle 'Appropriate' behaviour?

Edit: Because I sure as hell don't want to be the one to canonically whitelist all acceptable behaviour, which is what this issue appears to suggest?

**Comment by paulgregg** [comment]
I'd point to ITC's CoC as a good starting point.
https://irishtechcommunity.com/codeofconduct/

It has a whole paragraph on SFW and a list of specifically banned things.

Edit: @andrewbolster I didn't say we need to "canonically whitelist all acceptable behaviour" - I proposed that such a paragraph of acceptable behaviour would be couched in terms of saying all activity should be "Safe For Work".

**Comment by andrewbolster** [comment]
Looks like #29 should sort the spirit of this issue @paulgregg ?
